name: CI/CD for dbt Models

on:
  pull_request:
    branches:
      - master

jobs:
  test-and-deploy:
    name: Test and Deploy to Production
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Upgrade pip and setuptools
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 4: Set up virtual environment and install dependencies
    - name: Set up Virtual Environment
      run: |
        python -m venv dbt_bigquery_venv
        source dbt_bigquery_venv/bin/activate
        pip install dbt-bigquery==1.8.3
        pip install -r requirements.txt

    # Step 5: Verify the GOOGLE_CREDENTIALS Secret
    - name: Verify GOOGLE_CREDENTIALS Secret
      run: |
        if [ -z "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then
          echo "GOOGLE_CREDENTIALS is not set"
          exit 1
        else
          echo "GOOGLE_CREDENTIALS is set"
        fi

    # Step 6: Create gcp-key.json and profiles.yml
    - name: Create GCP Key and profiles.yml
      run: |
        mkdir -p /home/runner/.dbt

        # Write the Google credentials JSON file
        printf "%s" "${{ secrets.GOOGLE_CREDENTIALS }}" > /home/runner/.dbt/gcp-key.json

        # Dynamically generate profiles.yml
        cat <<EOF > /home/runner/.dbt/profiles.yml
        healthcare_dbt_bigquery_data_pipeline:
          outputs:
            dev:
              dataset: dev_healthcare_data
              job_execution_timeout_seconds: 300
              job_retries: 1
              keyfile: /home/runner/.dbt/gcp-key.json
              location: europe-west3
              method: service-account
              priority: interactive
              project: healthcare-data-project-442109
              threads: 4
              type: bigquery

            prod:
              dataset: prod_healthcare_data
              job_execution_timeout_seconds: 300
              job_retries: 1
              keyfile: /home/runner/.dbt/gcp-key.json
              location: europe-west3
              method: service-account
              priority: interactive
              project: healthcare-data-project-442109
              threads: 4
              type: bigquery

          target: dev
        EOF

        # Debugging: Verify the files were created successfully
        echo "Contents of gcp-key.json:"
        cat /home/runner/.dbt/gcp-key.json | head -n 10
        echo "Contents of profiles.yml:"
        cat /home/runner/.dbt/profiles.yml

    # Step 7: Run dbt Tests
    - name: Run dbt Tests
      run: |
        source dbt_bigquery_venv/bin/activate
        dbt test --profiles-dir /home/runner/.dbt --target dev

    # Step 8: Deploy to Production
    - name: Deploy to Production
      if: github.event.pull_request.merged == true
      run: |
        source dbt_bigquery_venv/bin/activate
        dbt run --profiles-dir /home/runner/.dbt --target prod
